DELETE FROM artist CASCADE;
DELETE FROM impresario CASCADE;
DELETE FROM impresario_artist_jenre CASCADE;
DELETE FROM event CASCADE;
DELETE FROM building CASCADE;
DELETE FROM theatre CASCADE;
DELETE FROM cinema CASCADE;
DELETE FROM artist_event CASCADE;